
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 15 20:53:54 MST 2021
//----------------------------------------------------

package Backend;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 25;
  public static final int Op_in_de_cremento = 26;
  public static final int Op_decremento = 41;
  public static final int Llave_c = 30;
  public static final int Llave_a = 29;
  public static final int If = 5;
  public static final int dosPuntos = 34;
  public static final int T_dato = 19;
  public static final int Op_asig = 20;
  public static final int delay_ms = 6;
  public static final int coma = 42;
  public static final int Else = 8;
  public static final int Sig_Agru = 39;
  public static final int Kp_Teclado = 38;
  public static final int Corchete_c = 32;
  public static final int Op_Resta = 22;
  public static final int Corchete_a = 31;
  public static final int pulsa = 9;
  public static final int TK_punto = 40;
  public static final int While = 4;
  public static final int Final = 13;
  public static final int Display = 12;
  public static final int For = 3;
  public static final int EOF = 0;
  public static final int P_coma = 33;
  public static final int error = 1;
  public static final int retnot = 2;
  public static final int Op_Division = 24;
  public static final int ERRORL_000 = 37;
  public static final int KeyPlayed = 11;
  public static final int parentesis_c = 28;
  public static final int parentesis_a = 27;
  public static final int caso = 15;
  public static final int Identificador = 35;
  public static final int pines_B = 18;
  public static final int Op_Multiplicacion = 23;
  public static final int output_low = 17;
  public static final int Numero = 36;
  public static final int star = 7;
  public static final int Op_Suma = 21;
  public static final int output_high = 16;
  public static final int event = 14;
  public static final int output_N = 10;
}

