/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backend;

/**
 *
 * @author Cristopher
 */
public enum Tokens {
    /*
    Reservada("Reservada"),
    TK_Sig_Punt("Signo Puntuación"),
    TK_Sig_Agrup("Signo Agrupación"),
    TK_Op_Incremento("Operador Incremento"),
    TK_Op_Disminucion("Operador Disminución"),
    TK_Op_Relacional("Operador Relacional"),
    TK_Op_Arit("Operador Aritmetico"),
    TK_Op_Logi("Operador Logico"),
    TK_Op_Desigual("Operador Desigual"),
    TK_Op_Asig("Operador Asignación"),
    //TK_Boleanos("Boleano"),
    IDENTIFICADOR("Identificador"),
    Num("Num"),
    //CADENA("Cadena"),
    ERRORL_000("Error Lexico 000"),
    ERRORL_001("Error Lexico 001"),
    ERRORL_002("Error Lexico 002"),
    ERRORL_003("Error Lexico 003"),
    ERRORL_004("Error Lexico 004"),
    ERRORL_005("Error Lexico 005"),
    ERRORL_006("Error Lexico 006"),
    ERRORL_007("Error Lexico 007"),
    ERRORL_008("Error Lexico 008"),
    ERRORL_009("Error Lexico 009"),
    ERRORL_010("Error Lexico 010");
    */
    //DUPLICADO PARA ANALISIS SINTACTICO
    retnot,
    For,
    While,
    If,
    delay_ms,
    star,
    Else,
    T_dato,
    Valor_fal,
    Valor_ver,
    pulsa,
    output_N,
    Kp_Teclado,
    KeyPlayed,
    Display,
    Final,
    event,
    caso,
    output_high,
    output_low,
    pines_B,
    Sig_Agru,
    dosPuntos,
    Llave_a,
    Llave_c,
    Corchete_a,
    Corchete_c,
    parentesis_a,
    parentesis_c,
    TK_punto,
    Op_incremento,
    Op_decremento,
    Op_relacional,
    Op_Suma,
    Op_Resta,
    Op_Multiplicacion,
    Op_Division,
    Op_asig,
    P_coma,
    Identificador,
    Numero,
    ERRORL_000,
    ERRORL_001,
    ERRORL_002,
    ERRORL_003,
    ERRORL_004,
    ERRORL_005,
    ERRORL_006,
    ERRORL_007,
    ERRORL_008,
    ERRORL_009,
    ERRORL_010,
    ERRORL_011,
    ERRORL_012,
    ERRORL_013,
    ERRORL_014,
    ERRORL_015,
    ERRORL_016;
     
}
